[package]
name = "stm32f3-gpio"
version = "0.1.0"
authors = ["Jan Teske <jteske@posteo.net>"]
edition = "2018"

[dependencies]
bare-metal = "0.2"
vcell = "0.1"

[features]
f302 = []
f303 = []
f303e = []
f333 = []
f373 = []
